### PR TITLE
remove Mapzen location lookup

### PR DESCRIPTION
**Pull request by Abbe98**
Seems to fix the tool.

### CODE REVIEW

**Comment by Abbe98** [comment]
@lokal-profil I can deploy the fix but not merge it :-)

**Comment by tohaklim** [comment]
this won't fix CSP though?

**Comment by lokal-profil** [comment]
> this won't fix CSP though?

Not sure I get your reference?

**Comment by tohaklim** [comment]
Last time I checked, m2c was broken in Chrome and any other browser enforcing CSP

**Comment by lokal-profil** [comment]
@tohaklim thanks. That's likely a separate issue. I don't know enough about CSP to fix it though (if fixable)

**Comment by Abbe98** [comment]
@tohaklim tool server does not enforce CSP, I just tested in Chromium and Firefox.

**Comment by tohaklim** [comment]
I'm getting this with mapillary2commons

app.js:85 [Report Only] Refused to connect to 'https://a.mapillary.com/v3/images/' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval' 'unsafe-inline' blob: data: filesystem: mediastream: wikibooks.org *.wikibooks.org wikidata.org *.wikidata.org wikimedia.org *.wikimedia.org wikinews.org *.wikinews.org wikipedia.org *.wikipedia.org wikiquote.org *.wikiquote.org wikisource.org *.wikisource.org wikiversity.org *.wikiversity.org wikivoyage.org *.wikivoyage.org wiktionary.org *.wiktionary.org *.wmflabs.org wikimediafoundation.org mediawiki.org *.mediawiki.org wss://tools.wmflabs.org". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by Abbe98** [comment]
@tohaklim That error shouldn't cause the loading of the Mapillary API to fail. As the error says it's "Report only" and should not be enforced.

Have you tried to actually upload a Mapillary file?

**Comment by tohaklim** [comment]
@Abbe98 indeed, it does work! weird, it must have been fixed at some point since I do remember it being broken

**Pull request merged**
